# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ThinkPads.org
email: smclt30p@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    We are a small team that is here to bring you the best user 
    experience on your IBM/Lenovo ThinkPad.
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://thinkpads.org" # the base hostname & protocol for your site
github_username:  libthinkpad

plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname: thinkpads-org-1

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
